# API Keys for Streamlit Cloud
# Replace with your actual keys when deploying

OPENROUTER_API_KEY = "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"
OPENWEATHER_API_KEY = "your_key_here" 

[google]
GEMINI_API_KEY = "your_key_here"

[general]
LLM_MODE = "google" 